import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load the linear regression model weights generated by train_linear_model.py
const weightsPath = path.join(__dirname, "..", "config", "model_weights.json");
let modelWeights = null;

try {
  if (fs.existsSync(weightsPath)) {
    const rawData = fs.readFileSync(weightsPath, "utf-8");
    modelWeights = JSON.parse(rawData);
    console.log("Successfully loaded Linear Regression model weights for risk prediction.");
  } else {
    console.warn("model_weights.json not found! Falling back to rule-based evaluation.");
  }
} catch (error) {
  console.error("Error loading model weights:", error);
}

const clamp = (value, min = 0, max = 100) => Math.max(min, Math.min(max, Number(value) || 0));

function getRiskLevel(riskIndex) {
  const percentage = riskIndex * 100;
  if (percentage >= 75) return "Critical";
  if (percentage >= 55) return "High";
  if (percentage >= 30) return "Moderate";
  return "Low";
}

function getLeadTime(riskIndex) {
  const percentage = riskIndex * 100;
  if (percentage >= 75) return "0–2 hours";
  if (percentage >= 55) return "2–6 hours";
  if (percentage >= 30) return "6–24 hours";
  return "24+ hours";
}

function predictWithLinearRegression(input) {
  // Map input to the 28 features used during training
  const featureValues = {
    "rainfall_15min_mm": (input.rainfall || 0) * 0.25,
    "rainfall_1h_mm": input.rainfall || 0,
    "rainfall_3h_mm": (input.rainfall || 0) * 2.5,
    "rainfall_6h_mm": (input.rainfall || 0) * 4.0,
    "rainfall_12h_mm": (input.rainfall || 0) * 6.0,
    "rainfall_24h_mm": (input.rainfall || 0) * 10.0,
    "rainfall_72h_mm": (input.rainfall || 0) * 20.0,
    "forecast_rainfall_1h_mm": input.forecast_rainfall || (input.rainfall || 0),
    "forecast_rainfall_3h_mm": (input.forecast_rainfall || (input.rainfall || 0)) * 3.0,
    "forecast_rainfall_6h_mm": (input.forecast_rainfall || (input.rainfall || 0)) * 5.0,
    "soil_moisture_pct": input.soilMoisture || 60,
    "soil_moisture_change_3h_pct": input.soilMoistureChange || 0,
    "water_level_m": input.waterLevel || 5.0,
    "water_level_change_1h_m": input.waterLevelChange || 0.0,
    "temperature_c": input.temperature || 28.0,
    "humidity_pct": input.humidity || 80.0,
    "latitude": input.latitude || 26.2,
    "longitude": input.longitude || 92.9,
    "elevation_m": input.elevation || 150.0,
    "slope_degree": input.slope || (100 - (input.slopeStability || 80)),
    "catchment_area_km2": input.catchmentArea || 50.0,
    "distance_to_river_km": input.distanceToRiver || 1.0,
    "historical_flood_frequency": input.historicalRisk ? input.historicalRisk / 10 : 2,
    "historical_landslide_frequency": input.historicalRisk ? input.historicalRisk / 20 : 1,
    "flood_susceptibility_score": input.floodSusceptibility || 0.5,
    "landslide_susceptibility_score": input.landslideSusceptibility || 0.5,
    "sensor_data_available": 1,
    "data_quality_score": 0.9
  };

  const { features, scaler, flood_model, landslide_model } = modelWeights;

  // Scale features
  const scaledVector = features.map((feature, i) => {
    const val = featureValues[feature] || 0;
    const mean = scaler.mean[i];
    const scale = scaler.scale[i];
    return (val - mean) / scale;
  });

  // Calculate flood risk
  let floodRiskIndex = flood_model.intercept;
  for (let i = 0; i < features.length; i++) {
    floodRiskIndex += scaledVector[i] * flood_model.coefficients[i];
  }
  floodRiskIndex = clamp(floodRiskIndex, 0, 1);

  // Calculate landslide risk
  let landslideRiskIndex = landslide_model.intercept;
  for (let i = 0; i < features.length; i++) {
    landslideRiskIndex += scaledVector[i] * landslide_model.coefficients[i];
  }
  landslideRiskIndex = clamp(landslideRiskIndex, 0, 1);

  const overallRiskIndex = (floodRiskIndex + landslideRiskIndex) / 2;

  return {
    rainfall: featureValues.rainfall_1h_mm,
    soilMoisture: featureValues.soil_moisture_pct,
    slopeStability: clamp(100 - featureValues.slope_degree),
    historicalRisk: featureValues.historical_flood_frequency * 10,
    floodRisk: Math.round(floodRiskIndex * 100),
    landslideRisk: Math.round(landslideRiskIndex * 100),
    overallRisk: Math.round(overallRiskIndex * 100),
    riskLevel: getRiskLevel(overallRiskIndex),
    leadTime: getLeadTime(overallRiskIndex),
    modelVersion: "LinearRegression-v1",
    factors: extractFactors(featureValues)
  };
}

function extractFactors(f) {
  const factors = [];
  if (f.rainfall_1h_mm >= 50) factors.push("Extreme current rainfall");
  if (f.forecast_rainfall_3h_mm >= 75) factors.push("Heavy forecast rainfall");
  if (f.soil_moisture_pct >= 80) factors.push("High soil saturation");
  if (f.water_level_change_1h_m >= 0.25) factors.push("Rapid river water level rise");
  if (f.slope_degree >= 25) factors.push("Steep terrain / Landslide risk");
  if (factors.length === 0) factors.push("Sustained hydrological baseline");
  return factors;
}

export function calculateRisk(input) {
  if (modelWeights) {
    return predictWithLinearRegression(input);
  }

  // Fallback to rule engine if weights are missing
  const rain = clamp(input.rainfall, 0, 150);
  const moisture = clamp(input.soilMoisture);
  const stability = clamp(input.slopeStability || 100);
  const history = clamp(input.historicalRisk);

  const rainRisk = clamp((rain / 150) * 100);
  const floodRisk = Math.round(0.55 * rainRisk + 0.25 * moisture + 0.2 * history);
  const instability = 100 - stability;
  const landslideRisk = Math.round(0.4 * rainRisk + 0.35 * instability + 0.15 * moisture + 0.1 * history);

  const overallRisk = Math.round(0.5 * floodRisk + 0.5 * landslideRisk);
  const riskLevel = getRiskLevel(overallRisk / 100);
  const leadTime = getLeadTime(overallRisk / 100);

  return {
    rainfall: rain,
    soilMoisture: moisture,
    slopeStability: stability,
    historicalRisk: history,
    floodRisk,
    landslideRisk,
    overallRisk,
    riskLevel,
    leadTime,
    modelVersion: "rule-engine-fallback"
  };
}
